server:
  port: 9999

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MahadevT/Olx-Config
          username: MahadevT
          password: gitloveu@143
          default-label: main
          clone-on-start: true